apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    getambassador.io/rolloutId: 47215624-babf-4623-be1e-561d57aa898a
  creationTimestamp: null
  name: rollout-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rollout-demo
  strategy:
    canary:
      canaryService: rollout-demo-canary
      stableService: rollout-demo
      steps:
      - setWeight: 30
      - pause:
          duration: 200
      - setWeight: 60
      - pause:
          duration: 200
      - setWeight: 90
      - pause:
          duration: 200
      trafficRouting:
        ambassador:
          mappings:
          - rollout-demo-mapping
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rollout-demo
    spec:
      containers:
      - args:
        - -text=VERSION 1
        - -listen=:8080
        image: hashicorp/http-echo:0.2.1
        imagePullPolicy: Always
        name: echo-v1
        ports:
        - containerPort: 8080
        resources: {}
status:
  blueGreen: {}
  canary: {}
